/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FortuneTiger {
  export type ActionStruct = {
    id: BigNumberish;
    creator: AddressLike;
    description: string;
    actionType: BigNumberish;
    status: BigNumberish;
    endTime: BigNumberish;
    totalPot: BigNumberish;
    creatorStake: BigNumberish;
    isStakeReturned: boolean;
    beneficiary: AddressLike;
    totalCoupons: BigNumberish;
    winner: AddressLike;
    closingBlock: BigNumberish;
    winningCoupon: BigNumberish;
  };

  export type ActionStructOutput = [
    id: bigint,
    creator: string,
    description: string,
    actionType: bigint,
    status: bigint,
    endTime: bigint,
    totalPot: bigint,
    creatorStake: bigint,
    isStakeReturned: boolean,
    beneficiary: string,
    totalCoupons: bigint,
    winner: string,
    closingBlock: bigint,
    winningCoupon: bigint
  ] & {
    id: bigint;
    creator: string;
    description: string;
    actionType: bigint;
    status: bigint;
    endTime: bigint;
    totalPot: bigint;
    creatorStake: bigint;
    isStakeReturned: boolean;
    beneficiary: string;
    totalCoupons: bigint;
    winner: string;
    closingBlock: bigint;
    winningCoupon: bigint;
  };
}

export interface FortuneTigerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COUPONS_PER_BKC"
      | "DRAW_MAX_OFFSET_BLOCKS"
      | "actionCounter"
      | "actions"
      | "bkcToken"
      | "couponOwners"
      | "couponRanges"
      | "createAction"
      | "ecosystemManager"
      | "finalizeAction"
      | "getAction"
      | "getMinCreatorStake"
      | "getParticipants"
      | "owner"
      | "participate"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionCreated"
      | "ActionFinalized"
      | "CreationFeePaid"
      | "OwnershipTransferred"
      | "Participation"
      | "StakeReturned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COUPONS_PER_BKC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DRAW_MAX_OFFSET_BLOCKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "actionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "actions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "bkcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "couponOwners",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "couponRanges",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAction",
    values: [BigNumberish, BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ecosystemManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinCreatorStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "participate",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "COUPONS_PER_BKC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DRAW_MAX_OFFSET_BLOCKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "actionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "actions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bkcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "couponOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "couponRanges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ecosystemManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMinCreatorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ActionCreatedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    creator: AddressLike,
    actionType: BigNumberish,
    endTime: BigNumberish,
    description: string
  ];
  export type OutputTuple = [
    actionId: bigint,
    creator: string,
    actionType: bigint,
    endTime: bigint,
    description: string
  ];
  export interface OutputObject {
    actionId: bigint;
    creator: string;
    actionType: bigint;
    endTime: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionFinalizedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    finalRecipient: AddressLike,
    prizeAmount: BigNumberish
  ];
  export type OutputTuple = [
    actionId: bigint,
    finalRecipient: string,
    prizeAmount: bigint
  ];
  export interface OutputObject {
    actionId: bigint;
    finalRecipient: string;
    prizeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreationFeePaidEvent {
  export type InputTuple = [creator: AddressLike, feeAmount: BigNumberish];
  export type OutputTuple = [creator: string, feeAmount: bigint];
  export interface OutputObject {
    creator: string;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipationEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    participant: AddressLike,
    bkcAmount: BigNumberish,
    couponsIssued: BigNumberish
  ];
  export type OutputTuple = [
    actionId: bigint,
    participant: string,
    bkcAmount: bigint,
    couponsIssued: bigint
  ];
  export interface OutputObject {
    actionId: bigint;
    participant: string;
    bkcAmount: bigint;
    couponsIssued: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeReturnedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    creator: AddressLike,
    stakeAmount: BigNumberish
  ];
  export type OutputTuple = [
    actionId: bigint,
    creator: string,
    stakeAmount: bigint
  ];
  export interface OutputObject {
    actionId: bigint;
    creator: string;
    stakeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FortuneTiger extends BaseContract {
  connect(runner?: ContractRunner | null): FortuneTiger;
  waitForDeployment(): Promise<this>;

  interface: FortuneTigerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COUPONS_PER_BKC: TypedContractMethod<[], [bigint], "view">;

  DRAW_MAX_OFFSET_BLOCKS: TypedContractMethod<[], [bigint], "view">;

  actionCounter: TypedContractMethod<[], [bigint], "view">;

  actions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: bigint;
        creator: string;
        description: string;
        actionType: bigint;
        status: bigint;
        endTime: bigint;
        totalPot: bigint;
        creatorStake: bigint;
        isStakeReturned: boolean;
        beneficiary: string;
        totalCoupons: bigint;
        winner: string;
        closingBlock: bigint;
        winningCoupon: bigint;
      }
    ],
    "view"
  >;

  bkcToken: TypedContractMethod<[], [string], "view">;

  couponOwners: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  couponRanges: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  createAction: TypedContractMethod<
    [
      _duration: BigNumberish,
      _actionType: BigNumberish,
      _charityStake: BigNumberish,
      _description: string,
      _boosterTokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  ecosystemManager: TypedContractMethod<[], [string], "view">;

  finalizeAction: TypedContractMethod<
    [_actionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAction: TypedContractMethod<
    [_actionId: BigNumberish],
    [FortuneTiger.ActionStructOutput],
    "view"
  >;

  getMinCreatorStake: TypedContractMethod<[], [bigint], "view">;

  getParticipants: TypedContractMethod<
    [_actionId: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  participate: TypedContractMethod<
    [
      _actionId: BigNumberish,
      _bkcAmount: BigNumberish,
      _boosterTokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COUPONS_PER_BKC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DRAW_MAX_OFFSET_BLOCKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "actionCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "actions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: bigint;
        creator: string;
        description: string;
        actionType: bigint;
        status: bigint;
        endTime: bigint;
        totalPot: bigint;
        creatorStake: bigint;
        isStakeReturned: boolean;
        beneficiary: string;
        totalCoupons: bigint;
        winner: string;
        closingBlock: bigint;
        winningCoupon: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bkcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "couponOwners"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "couponRanges"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAction"
  ): TypedContractMethod<
    [
      _duration: BigNumberish,
      _actionType: BigNumberish,
      _charityStake: BigNumberish,
      _description: string,
      _boosterTokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ecosystemManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeAction"
  ): TypedContractMethod<[_actionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAction"
  ): TypedContractMethod<
    [_actionId: BigNumberish],
    [FortuneTiger.ActionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMinCreatorStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<
    [_actionId: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "participate"
  ): TypedContractMethod<
    [
      _actionId: BigNumberish,
      _bkcAmount: BigNumberish,
      _boosterTokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ActionCreated"
  ): TypedContractEvent<
    ActionCreatedEvent.InputTuple,
    ActionCreatedEvent.OutputTuple,
    ActionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ActionFinalized"
  ): TypedContractEvent<
    ActionFinalizedEvent.InputTuple,
    ActionFinalizedEvent.OutputTuple,
    ActionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "CreationFeePaid"
  ): TypedContractEvent<
    CreationFeePaidEvent.InputTuple,
    CreationFeePaidEvent.OutputTuple,
    CreationFeePaidEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Participation"
  ): TypedContractEvent<
    ParticipationEvent.InputTuple,
    ParticipationEvent.OutputTuple,
    ParticipationEvent.OutputObject
  >;
  getEvent(
    key: "StakeReturned"
  ): TypedContractEvent<
    StakeReturnedEvent.InputTuple,
    StakeReturnedEvent.OutputTuple,
    StakeReturnedEvent.OutputObject
  >;

  filters: {
    "ActionCreated(uint256,address,uint8,uint256,string)": TypedContractEvent<
      ActionCreatedEvent.InputTuple,
      ActionCreatedEvent.OutputTuple,
      ActionCreatedEvent.OutputObject
    >;
    ActionCreated: TypedContractEvent<
      ActionCreatedEvent.InputTuple,
      ActionCreatedEvent.OutputTuple,
      ActionCreatedEvent.OutputObject
    >;

    "ActionFinalized(uint256,address,uint256)": TypedContractEvent<
      ActionFinalizedEvent.InputTuple,
      ActionFinalizedEvent.OutputTuple,
      ActionFinalizedEvent.OutputObject
    >;
    ActionFinalized: TypedContractEvent<
      ActionFinalizedEvent.InputTuple,
      ActionFinalizedEvent.OutputTuple,
      ActionFinalizedEvent.OutputObject
    >;

    "CreationFeePaid(address,uint256)": TypedContractEvent<
      CreationFeePaidEvent.InputTuple,
      CreationFeePaidEvent.OutputTuple,
      CreationFeePaidEvent.OutputObject
    >;
    CreationFeePaid: TypedContractEvent<
      CreationFeePaidEvent.InputTuple,
      CreationFeePaidEvent.OutputTuple,
      CreationFeePaidEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Participation(uint256,address,uint256,uint256)": TypedContractEvent<
      ParticipationEvent.InputTuple,
      ParticipationEvent.OutputTuple,
      ParticipationEvent.OutputObject
    >;
    Participation: TypedContractEvent<
      ParticipationEvent.InputTuple,
      ParticipationEvent.OutputTuple,
      ParticipationEvent.OutputObject
    >;

    "StakeReturned(uint256,address,uint256)": TypedContractEvent<
      StakeReturnedEvent.InputTuple,
      StakeReturnedEvent.OutputTuple,
      StakeReturnedEvent.OutputObject
    >;
    StakeReturned: TypedContractEvent<
      StakeReturnedEvent.InputTuple,
      StakeReturnedEvent.OutputTuple,
      StakeReturnedEvent.OutputObject
    >;
  };
}
