/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ecosystemManagerSol from "./EcosystemManager.sol";
export type { ecosystemManagerSol };
export type { BKCToken } from "./BKCToken";
export type { DecentralizedNotary } from "./DecentralizedNotary";
export type { DelegationManager } from "./DelegationManager";
export type { FortuneTiger } from "./FortuneTiger";
export type { NFTLiquidityPool } from "./NFTLiquidityPool";
export type { PublicSale } from "./PublicSale";
export type { RewardBoosterNFT } from "./RewardBoosterNFT";
export type { RewardManager } from "./RewardManager";
export type { SimpleBKCFaucet } from "./SimpleBKCFaucet";
