// create-backchain-app — Project Generator
// ============================================================================

import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

/**
 * Generate a complete Backchain frontend project.
 * @param {string} dir - Project directory path
 * @param {object} config - { name, operator, network, modules }
 */
export function generateProject(dir, config) {
    mkdirSync(dir, { recursive: true });
    mkdirSync(join(dir, 'modules'), { recursive: true });

    // Core files
    writeFileSync(join(dir, 'package.json'), genPackageJson(config));
    writeFileSync(join(dir, 'vite.config.js'), genViteConfig());
    writeFileSync(join(dir, 'vercel.json'), genVercelJson());
    writeFileSync(join(dir, 'index.html'), genIndexHtml(config));
    writeFileSync(join(dir, 'main.js'), genMainJs(config));
    writeFileSync(join(dir, 'style.css'), genStyleCss());

    // Core pages — always included
    writeFileSync(join(dir, 'modules', 'dashboard.js'), genDashboard(config));
    writeFileSync(join(dir, 'modules', 'staking.js'), genStakingPage(config));
    writeFileSync(join(dir, 'modules', 'tutor.js'), genTutorPage(config));
    writeFileSync(join(dir, 'modules', 'tokenomics.js'), genTokenomicsPage(config));
    writeFileSync(join(dir, 'modules', 'invite.js'), genInvitePage(config));

    // Feature pages — user-selected
    const generators = {
        nft: genNftPage,
        fortune: genFortunePage,
        notary: genNotaryPage,
        agora: genAgoraPage,
        charity: genCharityPage,
        rental: genRentalPage,
        swap: genSwapPage,
        fusion: genFusionPage,
        buyback: genBuybackPage,
    };

    for (const mod of config.modules) {
        if (generators[mod]) {
            writeFileSync(join(dir, 'modules', `${mod}.js`), generators[mod](config));
        }
    }
}

// ── Package.json ────────────────────────────────────────────────────────────

function genPackageJson(config) {
    return JSON.stringify({
        name: config.name,
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview',
        },
        dependencies: {
            '@backchain/sdk': '^0.2.0',
            ethers: '^6.13.0',
        },
        devDependencies: {
            vite: '^6.0.0',
        },
    }, null, 2) + '\n';
}

// ── Vite Config ─────────────────────────────────────────────────────────────

function genViteConfig() {
    return `import { defineConfig } from 'vite';

export default defineConfig({
    build: { target: 'esnext' },
});
`;
}

// ── Vercel.json ─────────────────────────────────────────────────────────────

function genVercelJson() {
    return JSON.stringify({
        rewrites: [{ source: '/(.*)', destination: '/index.html' }],
    }, null, 2) + '\n';
}

// ── Style.css ───────────────────────────────────────────────────────────────

function genStyleCss() {
    return `/* Backchain App — Generated by create-backchain-app */

:root {
    --bg: #09090b;
    --surface: #18181b;
    --border: #27272a;
    --text: #e4e4e7;
    --text-dim: #71717a;
    --accent: #f59e0b;
    --accent-hover: #d97706;
    --success: #22c55e;
    --error: #ef4444;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    background: var(--bg);
    color: var(--text);
    min-height: 100vh;
}

.app { display: flex; min-height: 100vh; }

/* ── Sidebar ─────────────────────────────────────────── */
.sidebar {
    width: 240px;
    background: var(--surface);
    border-right: 1px solid var(--border);
    padding: 24px 16px;
    display: flex;
    flex-direction: column;
    gap: 4px;
    position: fixed;
    top: 0;
    bottom: 0;
    overflow-y: auto;
}

.sidebar-brand {
    font-size: 1.25rem;
    font-weight: 700;
    color: white;
    padding: 0 12px 20px;
    border-bottom: 1px solid var(--border);
    margin-bottom: 12px;
}

.sidebar-brand span { color: var(--accent); }

.nav-link {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 12px;
    border-radius: 8px;
    color: var(--text-dim);
    text-decoration: none;
    font-size: 0.875rem;
    transition: all 0.15s;
}

.nav-link:hover { color: var(--text); background: rgba(255,255,255,0.05); }
.nav-link.active { color: var(--accent); background: rgba(245,158,11,0.1); }

.nav-icon { width: 20px; text-align: center; }

.sidebar-footer {
    margin-top: auto;
    padding-top: 16px;
    border-top: 1px solid var(--border);
    font-size: 0.75rem;
    color: var(--text-dim);
    text-align: center;
}

.sidebar-footer a { color: var(--accent); text-decoration: none; }

/* ── Main Content ────────────────────────────────────── */
.main { margin-left: 240px; flex: 1; padding: 32px; max-width: 900px; }

.page { display: none; }
.page.active { display: block; }

.page-title {
    font-size: 1.5rem;
    font-weight: 700;
    margin-bottom: 24px;
}

/* ── Cards ───────────────────────────────────────────── */
.card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 24px;
    margin-bottom: 16px;
}

.card-title {
    font-size: 1rem;
    font-weight: 600;
    margin-bottom: 12px;
    color: white;
}

/* ── Buttons ─────────────────────────────────────────── */
.btn {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 10px 20px;
    border-radius: 8px;
    font-size: 0.875rem;
    font-weight: 600;
    border: none;
    cursor: pointer;
    transition: all 0.15s;
}

.btn-primary {
    background: var(--accent);
    color: #000;
}

.btn-primary:hover { background: var(--accent-hover); }

.btn-secondary {
    background: transparent;
    color: var(--text);
    border: 1px solid var(--border);
}

.btn-secondary:hover { border-color: var(--text-dim); }

.btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
}

/* ── Forms ───────────────────────────────────────────── */
.input {
    width: 100%;
    padding: 10px 14px;
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 8px;
    color: var(--text);
    font-size: 0.875rem;
    outline: none;
    transition: border-color 0.15s;
}

.input:focus { border-color: var(--accent); }

.form-group { margin-bottom: 16px; }
.form-label {
    display: block;
    font-size: 0.8rem;
    color: var(--text-dim);
    margin-bottom: 6px;
    font-weight: 500;
}

/* ── Stats Grid ──────────────────────────────────────── */
.stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 12px;
    margin-bottom: 20px;
}

.stat-card {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 16px;
}

.stat-label { font-size: 0.75rem; color: var(--text-dim); margin-bottom: 4px; }
.stat-value { font-size: 1.25rem; font-weight: 700; color: white; }
.stat-value.accent { color: var(--accent); }

/* ── Toast ───────────────────────────────────────────── */
.toast-container {
    position: fixed;
    top: 16px;
    right: 16px;
    z-index: 9999;
    display: flex;
    flex-direction: column;
    gap: 8px;
}

.toast {
    padding: 12px 20px;
    border-radius: 8px;
    font-size: 0.875rem;
    color: white;
    animation: slideIn 0.3s ease;
}

.toast.success { background: #166534; border: 1px solid #22c55e; }
.toast.error { background: #7f1d1d; border: 1px solid #ef4444; }
.toast.info { background: #1e3a5f; border: 1px solid #3b82f6; }

@keyframes slideIn {
    from { transform: translateX(100%); opacity: 0; }
    to { transform: translateX(0); opacity: 1; }
}

/* ── Wallet Badge ────────────────────────────────────── */
.wallet-badge {
    padding: 8px 12px;
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 8px;
    font-size: 0.8rem;
    color: var(--accent);
    font-family: monospace;
}

/* ── Responsive ──────────────────────────────────────── */
@media (max-width: 768px) {
    .sidebar { width: 60px; padding: 16px 8px; }
    .sidebar-brand span, .nav-link span, .sidebar-footer { display: none; }
    .nav-link { justify-content: center; padding: 10px; }
    .main { margin-left: 60px; padding: 16px; }
    .stats-grid { grid-template-columns: 1fr 1fr; }
}
`;
}

// ── index.html ──────────────────────────────────────────────────────────────

function genIndexHtml(config) {
    // Core nav items (always present)
    const navItems = [
        { id: 'dashboard', icon: '&#9632;', label: 'Dashboard' },
        { id: 'staking', icon: '&#9733;', label: 'Stake & Earn' },
    ];

    // Feature nav items (user-selected)
    const featureNav = {
        nft: { icon: '&#9830;', label: 'NFT Store' },
        fortune: { icon: '&#9752;', label: 'Fortune Pool' },
        notary: { icon: '&#9998;', label: 'Notary' },
        agora: { icon: '&#9993;', label: 'Agora' },
        charity: { icon: '&#9829;', label: 'Charity' },
        rental: { icon: '&#8962;', label: 'Rental' },
        swap: { icon: '&#8646;', label: 'Swap' },
        fusion: { icon: '&#9878;', label: 'Fusion' },
        buyback: { icon: '&#8635;', label: 'Buyback' },
    };

    for (const mod of config.modules) {
        if (featureNav[mod]) navItems.push({ id: mod, ...featureNav[mod] });
    }

    // Core nav items at bottom
    navItems.push(
        { id: 'tutor', icon: '&#9734;', label: 'Tutor System' },
        { id: 'invite', icon: '&#9993;', label: 'Invite & Earn' },
        { id: 'tokenomics', icon: '&#9673;', label: 'Tokenomics' },
    );

    const navHtml = navItems.map(n =>
        `            <a href="#${n.id}" class="nav-link" data-page="${n.id}">
                <span class="nav-icon">${n.icon}</span>
                <span>${n.label}</span>
            </a>`
    ).join('\n');

    const pageSlots = navItems.map(n =>
        `        <div id="page-${n.id}" class="page"></div>`
    ).join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${config.name} — Powered by Backchain</title>
    <link rel="stylesheet" href="./style.css">
</head>
<body>
    <div class="app">
        <nav class="sidebar">
            <div class="sidebar-brand">Back<span>chain</span></div>
${navHtml}
            <div class="sidebar-footer">
                <div id="walletStatus">Not connected</div>
                <br>
                <a href="https://backcoin.org" target="_blank">backcoin.org</a>
            </div>
        </nav>

        <main class="main">
            <div id="connectPrompt" style="text-align:center;padding:60px 20px;">
                <h2 style="margin-bottom:16px;">Connect Your Wallet</h2>
                <p style="color:var(--text-dim);margin-bottom:24px;">Connect MetaMask to start using the app</p>
                <button id="connectBtn" class="btn btn-primary">Connect Wallet</button>
            </div>

${pageSlots}
        </main>
    </div>

    <div class="toast-container" id="toasts"></div>

    <script type="module" src="./main.js"></script>
</body>
</html>
`;
}

// ── main.js ─────────────────────────────────────────────────────────────────

function genMainJs(config) {
    const CORE_MODULES = ['staking', 'tutor', 'tokenomics', 'invite'];
    const allModules = [...CORE_MODULES, ...config.modules];

    const moduleImports = allModules.map(m =>
        `import { render as render${capitalize(m)}, load as load${capitalize(m)} } from './modules/${m}.js';`
    ).join('\n');

    const moduleRenders = ['dashboard', ...allModules].map(m =>
        `        case '${m}': await render${capitalize(m)}(document.getElementById('page-${m}'), bkc); break;`
    ).join('\n');

    const moduleLoads = allModules.map(m =>
        `            try { await load${capitalize(m)}(bkc); } catch(e) { console.warn('${m} load:', e.message); }`
    ).join('\n');

    return `// ${config.name} — Generated by create-backchain-app
// Operator: ${config.operator}

import { Backchain } from '@backchain/sdk';
import { ethers } from 'ethers';
import { render as renderDashboard, load as loadDashboard } from './modules/dashboard.js';
${moduleImports}

// ── SDK Instance ────────────────────────────────────────────────────────────
const bkc = new Backchain({
    operator: '${config.operator}',
    network: '${config.network}',
});

// ── Global Helpers ──────────────────────────────────────────────────────────
window.bkc = bkc;
window.ethers = ethers;
window.fmt = (wei) => ethers.formatEther(wei);
window.parse = (eth) => ethers.parseEther(eth);

export function toast(msg, type = 'info') {
    const div = document.createElement('div');
    div.className = 'toast ' + type;
    div.textContent = msg;
    document.getElementById('toasts').appendChild(div);
    setTimeout(() => div.remove(), 4000);
}

// ── Router ──────────────────────────────────────────────────────────────────
let currentPage = null;

async function navigate(page) {
    document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
    document.querySelectorAll('.nav-link').forEach(l => l.classList.remove('active'));

    const el = document.getElementById('page-' + page);
    const link = document.querySelector('[data-page="' + page + '"]');
    if (el) el.classList.add('active');
    if (link) link.classList.add('active');

    currentPage = page;

    switch (page) {
${moduleRenders}
    }
}

// ── Wallet Connection ───────────────────────────────────────────────────────
async function connectWallet() {
    try {
        const address = await bkc.connect();
        document.getElementById('connectPrompt').style.display = 'none';
        document.getElementById('walletStatus').innerHTML =
            '<span class="wallet-badge">' + address.slice(0, 6) + '...' + address.slice(-4) + '</span>';
        toast('Wallet connected!', 'success');

        // Load data for all modules
        try { await loadDashboard(bkc); } catch(e) { console.warn('dashboard load:', e.message); }
${moduleLoads}

        navigate(location.hash.slice(1) || 'dashboard');
    } catch (err) {
        toast(err.message, 'error');
    }
}

// ── Init ────────────────────────────────────────────────────────────────────
document.getElementById('connectBtn').addEventListener('click', connectWallet);

document.querySelectorAll('.nav-link').forEach(link => {
    link.addEventListener('click', (e) => {
        e.preventDefault();
        const page = link.dataset.page;
        location.hash = page;
        if (bkc.isConnected) navigate(page);
    });
});

window.addEventListener('hashchange', () => {
    if (bkc.isConnected) navigate(location.hash.slice(1) || 'dashboard');
});
`;
}

// ── Dashboard Page ──────────────────────────────────────────────────────────

function genDashboard(config) {
    return `// Dashboard — Account overview
import { ethers } from 'ethers';

let _data = {};

export async function load(bkc) {
    const [ethBal, bkcBal, earnings] = await Promise.all([
        bkc.getEthBalance(),
        bkc.getBkcBalance(),
        bkc.getPendingEarnings(),
    ]);
    _data = { ethBal, bkcBal, earnings };
}

export async function render(el, bkc) {
    if (!_data.ethBal) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">Dashboard</h1>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">ETH Balance</div>
                <div class="stat-value">\${fmt(\${JSON.stringify('_data.ethBal')})} ETH</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">BKC Balance</div>
                <div class="stat-value accent">\${fmt(\${JSON.stringify('_data.bkcBal')})} BKC</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Operator Earnings</div>
                <div class="stat-value">\${fmt(\${JSON.stringify('_data.earnings')})} ETH</div>
            </div>
        </div>

        <div class="card">
            <div class="card-title">Your Operator Address</div>
            <p style="font-family:monospace;color:var(--accent);word-break:break-all;">${config.operator}</p>
            <p style="color:var(--text-dim);font-size:0.85rem;margin-top:8px;">
                You earn 10-20% of every ETH fee generated through this app.
            </p>
        </div>

        <div class="card">
            <div class="card-title">Connected Wallet</div>
            <p style="font-family:monospace;word-break:break-all;">\${bkc.address}</p>
            <p style="color:var(--text-dim);font-size:0.85rem;margin-top:8px;">
                Network: ${config.network}
            </p>
        </div>
    \`;
}
`;
}

// ── Module Page Generators ──────────────────────────────────────────────────
// Each generates a self-contained module page with render() and load() exports.

function genStakingPage() {
    return `// Staking Module
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _data = {};

export async function load(bkc) {
    const [summary, stats] = await Promise.all([
        bkc.staking.getUserSummary(),
        bkc.staking.getStats(),
    ]);
    _data = { summary, stats };
}

export async function render(el, bkc) {
    if (!_data.summary) await load(bkc);
    const s = _data.summary;
    const g = _data.stats;

    el.innerHTML = \`
        <h1 class="page-title">Staking & Mining</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Your pStake</div>
                <div class="stat-value accent">\${Number(ethers.formatEther(s.userTotalPStake)).toLocaleString()}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Delegations</div>
                <div class="stat-value">\${s.delegationCount.toString()}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Pending Rewards</div>
                <div class="stat-value">\${Number(ethers.formatEther(s.totalPending)).toFixed(2)} BKC</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">NFT Boost</div>
                <div class="stat-value">\${Number(s.nftBoost) / 100}%</div>
            </div>
        </div>

        <div class="card">
            <div class="card-title">Delegate BKC</div>
            <div class="form-group">
                <label class="form-label">Amount (BKC)</label>
                <input type="number" id="stakeAmount" class="input" placeholder="100" />
            </div>
            <div class="form-group">
                <label class="form-label">Lock Period (days)</label>
                <input type="number" id="stakeDays" class="input" placeholder="365" min="1" max="3650" />
            </div>
            <button id="delegateBtn" class="btn btn-primary">Delegate</button>
        </div>

        <div class="card">
            <div class="card-title">Claim Rewards</div>
            <p style="color:var(--text-dim);font-size:0.85rem;margin-bottom:12px;">
                Recycle rate: \${Number(s.recycleRateBps) / 100}% — get an NFT Booster to reduce burn
            </p>
            <button id="claimBtn" class="btn btn-primary">Claim Rewards</button>
        </div>

        <div class="card">
            <div class="card-title">Network Stats</div>
            <p>Total pStake: \${Number(ethers.formatEther(g.totalPStake)).toLocaleString()}</p>
            <p>Total Delegated: \${Number(ethers.formatEther(g.totalBkcDelegated)).toLocaleString()} BKC</p>
            <p>Total Rewards: \${Number(ethers.formatEther(g.totalRewardsDistributed)).toLocaleString()} BKC</p>
        </div>
    \`;

    el.querySelector('#delegateBtn').onclick = async () => {
        try {
            const amount = ethers.parseEther(el.querySelector('#stakeAmount').value);
            const days = parseInt(el.querySelector('#stakeDays').value);
            const result = await bkc.staking.delegate(amount, days);
            toast('Delegated! TX: ' + result.hash.slice(0, 10) + '...', 'success');
            await load(bkc);
            render(el, bkc);
        } catch (err) { toast(err.message, 'error'); }
    };

    el.querySelector('#claimBtn').onclick = async () => {
        try {
            const result = await bkc.staking.claimRewards();
            toast('Rewards claimed! TX: ' + result.hash.slice(0, 10) + '...', 'success');
            await load(bkc);
            render(el, bkc);
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

function genNftPage() {
    return `// NFT Store Module
import { ethers } from 'ethers';
import { toast } from '../main.js';

const TIERS = ['Bronze', 'Silver', 'Gold', 'Diamond'];
const BOOSTS = ['10%', '25%', '40%', '50%'];
let _prices = [];

export async function load(bkc) {
    _prices = await Promise.all([0, 1, 2, 3].map(t => bkc.nft.getBuyPrice(t)));
}

export async function render(el, bkc) {
    if (!_prices.length) await load(bkc);

    const cards = TIERS.map((name, i) => \`
        <div class="card">
            <div class="card-title">\${name} NFT</div>
            <p style="color:var(--text-dim);margin-bottom:8px;">Boost: \${BOOSTS[i]}</p>
            <p>Price: \${Number(ethers.formatEther(_prices[i].bkcCost)).toFixed(2)} BKC + \${Number(ethers.formatEther(_prices[i].ethFee)).toFixed(6)} ETH</p>
            <button class="btn btn-primary" style="margin-top:12px;" data-tier="\${i}">Buy \${name}</button>
        </div>
    \`).join('');

    el.innerHTML = \`<h1 class="page-title">NFT Booster Store</h1>\${cards}\`;

    el.querySelectorAll('[data-tier]').forEach(btn => {
        btn.onclick = async () => {
            try {
                btn.disabled = true;
                btn.textContent = 'Buying...';
                const tier = parseInt(btn.dataset.tier);
                const result = await bkc.nft.buy(tier);
                toast(\`Bought \${TIERS[tier]} NFT! Token #\${result.events.tokenId}\`, 'success');
                await load(bkc);
                render(el, bkc);
            } catch (err) { toast(err.message, 'error'); btn.disabled = false; btn.textContent = 'Buy'; }
        };
    });
}
`;
}

function genFortunePage() {
    return `// Fortune Pool Module
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _stats = null;

export async function load(bkc) {
    _stats = await bkc.fortune.getPoolStats();
}

export async function render(el, bkc) {
    if (!_stats) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">Fortune Pool</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Prize Pool</div>
                <div class="stat-value accent">\${Number(ethers.formatEther(_stats.prizePool)).toLocaleString()} BKC</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Games Played</div>
                <div class="stat-value">\${_stats.totalGamesPlayed.toString()}</div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Play Fortune</div>
            <div class="form-group">
                <label class="form-label">Wager (BKC)</label>
                <input type="number" id="wager" class="input" placeholder="10" />
            </div>
            <div class="form-group">
                <label class="form-label">Your Guess (0-9)</label>
                <input type="number" id="guess" class="input" placeholder="7" min="0" max="9" />
            </div>
            <button id="playBtn" class="btn btn-primary">Play (Tier 0)</button>
            <p style="color:var(--text-dim);font-size:0.8rem;margin-top:12px;">
                Commit-reveal: you'll need to reveal after a few blocks to see your result.
            </p>
        </div>
    \`;

    el.querySelector('#playBtn').onclick = async () => {
        try {
            const wager = ethers.parseEther(el.querySelector('#wager').value);
            const guess = parseInt(el.querySelector('#guess').value);
            const { gameId, secret } = await bkc.fortune.play(wager, [guess], 1);
            toast(\`Game #\${gameId} committed! Save your secret to reveal later.\`, 'success');
            localStorage.setItem('fortune_' + gameId, JSON.stringify({ guesses: [guess], secret }));
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

function genNotaryPage() {
    return `// Notary Module
import { ethers } from 'ethers';
import { NotaryModule } from '@backchain/sdk';
import { toast } from '../main.js';

let _stats = null;

export async function load(bkc) {
    _stats = await bkc.notary.getStats();
}

export async function render(el, bkc) {
    if (!_stats) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">Notary — Document Certification</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Certificates Issued</div>
                <div class="stat-value">\${_stats.certCount.toString()}</div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Certify a Document</div>
            <div class="form-group">
                <label class="form-label">Document Text or Data</label>
                <textarea id="docContent" class="input" rows="4" placeholder="Paste document content..."></textarea>
            </div>
            <div class="form-group">
                <label class="form-label">Description</label>
                <input type="text" id="docMeta" class="input" placeholder="Contract v2.0" />
            </div>
            <button id="certifyBtn" class="btn btn-primary">Certify On-Chain</button>
        </div>
        <div class="card">
            <div class="card-title">Verify a Document</div>
            <div class="form-group">
                <label class="form-label">Document Hash (bytes32)</label>
                <input type="text" id="verifyHash" class="input" placeholder="0x..." />
            </div>
            <button id="verifyBtn" class="btn btn-secondary">Verify</button>
            <div id="verifyResult" style="margin-top:12px;"></div>
        </div>
    \`;

    el.querySelector('#certifyBtn').onclick = async () => {
        try {
            const content = el.querySelector('#docContent').value;
            const meta = el.querySelector('#docMeta').value;
            const hash = await NotaryModule.hashDocument(content);
            const { certId } = await bkc.notary.certify(hash, meta, 0);
            toast(\`Certified! ID: \${certId}, Hash: \${hash.slice(0, 16)}...\`, 'success');
        } catch (err) { toast(err.message, 'error'); }
    };

    el.querySelector('#verifyBtn').onclick = async () => {
        try {
            const hash = el.querySelector('#verifyHash').value;
            const cert = await bkc.notary.verify(hash);
            const div = el.querySelector('#verifyResult');
            if (cert.exists) {
                div.innerHTML = \`<p style="color:var(--success);">Certified by \${cert.owner.slice(0,10)}... on \${new Date(Number(cert.timestamp) * 1000).toLocaleDateString()}</p><p>\${cert.meta}</p>\`;
            } else {
                div.innerHTML = '<p style="color:var(--error);">Not found</p>';
            }
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

function genAgoraPage() {
    return `// Agora (Social) Module
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _stats = null;

export async function load(bkc) {
    _stats = await bkc.agora.getGlobalStats();
}

export async function render(el, bkc) {
    if (!_stats) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">Agora — Social Protocol</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Total Posts</div>
                <div class="stat-value">\${_stats.totalPosts.toString()}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Total Profiles</div>
                <div class="stat-value">\${_stats.totalProfiles.toString()}</div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Create Post</div>
            <div class="form-group">
                <textarea id="postContent" class="input" rows="3" placeholder="What's on your mind?"></textarea>
            </div>
            <button id="postBtn" class="btn btn-primary">Post (Free)</button>
        </div>
    \`;

    el.querySelector('#postBtn').onclick = async () => {
        try {
            const content = el.querySelector('#postContent').value;
            const { postId } = await bkc.agora.createPost(content, 0, 0);
            toast(\`Post #\${postId} created!\`, 'success');
            el.querySelector('#postContent').value = '';
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

function genCharityPage() {
    return `// Charity Module
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _stats = null;

export async function load(bkc) {
    _stats = await bkc.charity.getStats();
}

export async function render(el, bkc) {
    if (!_stats) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">Charity — Transparent Fundraising</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Campaigns</div>
                <div class="stat-value">\${_stats.campaignCount.toString()}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Total Donated</div>
                <div class="stat-value accent">\${Number(ethers.formatEther(_stats.totalDonated)).toFixed(4)} ETH</div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Donate to Campaign</div>
            <div class="form-group">
                <label class="form-label">Campaign ID</label>
                <input type="number" id="campaignId" class="input" placeholder="1" />
            </div>
            <div class="form-group">
                <label class="form-label">Amount (ETH)</label>
                <input type="number" id="donateAmount" class="input" placeholder="0.01" step="0.001" />
            </div>
            <button id="donateBtn" class="btn btn-primary">Donate</button>
        </div>
    \`;

    el.querySelector('#donateBtn').onclick = async () => {
        try {
            const id = BigInt(el.querySelector('#campaignId').value);
            const amount = ethers.parseEther(el.querySelector('#donateAmount').value);
            await bkc.charity.donate(id, amount);
            toast('Donation sent!', 'success');
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

function genRentalPage() {
    return `// NFT Rental Module
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _stats = null;

export async function load(bkc) {
    _stats = await bkc.rental.getStats();
}

export async function render(el, bkc) {
    if (!_stats) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">NFT Rental — AirBNFT</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Active Listings</div>
                <div class="stat-value">\${_stats.activeListings.toString()}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Total Rentals</div>
                <div class="stat-value">\${_stats.rentals.toString()}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Total Volume</div>
                <div class="stat-value accent">\${Number(ethers.formatEther(_stats.volume)).toFixed(4)} ETH</div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Rent an NFT Booster</div>
            <div class="form-group">
                <label class="form-label">Token ID</label>
                <input type="number" id="rentTokenId" class="input" placeholder="123" />
            </div>
            <button id="rentBtn" class="btn btn-primary">Rent (1 day)</button>
        </div>
    \`;

    el.querySelector('#rentBtn').onclick = async () => {
        try {
            const tokenId = BigInt(el.querySelector('#rentTokenId').value);
            await bkc.rental.rentNft(tokenId);
            toast('NFT rented!', 'success');
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

function genSwapPage() {
    return `// Swap Module (AMM)
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _stats = null;

export async function load(bkc) {
    _stats = await bkc.swap.getStats();
}

export async function render(el, bkc) {
    if (!_stats) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">Swap — ETH ↔ BKC</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">BKC Price</div>
                <div class="stat-value accent">\${Number(ethers.formatEther(_stats.currentPrice)).toFixed(8)} ETH</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">ETH Reserve</div>
                <div class="stat-value">\${Number(ethers.formatEther(_stats.ethReserve)).toFixed(4)}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">BKC Reserve</div>
                <div class="stat-value">\${Number(ethers.formatEther(_stats.bkcReserve)).toLocaleString()}</div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Buy BKC with ETH</div>
            <div class="form-group">
                <label class="form-label">ETH Amount</label>
                <input type="number" id="buyEthAmount" class="input" placeholder="0.01" step="0.001" />
            </div>
            <button id="buyBkcBtn" class="btn btn-primary">Buy BKC</button>
        </div>
        <div class="card">
            <div class="card-title">Sell BKC for ETH</div>
            <div class="form-group">
                <label class="form-label">BKC Amount</label>
                <input type="number" id="sellBkcAmount" class="input" placeholder="100" />
            </div>
            <button id="sellBkcBtn" class="btn btn-primary">Sell BKC</button>
        </div>
    \`;

    el.querySelector('#buyBkcBtn').onclick = async () => {
        try {
            const amount = ethers.parseEther(el.querySelector('#buyEthAmount').value);
            await bkc.swap.buyBkc(amount);
            toast('Swap complete!', 'success');
        } catch (err) { toast(err.message, 'error'); }
    };

    el.querySelector('#sellBkcBtn').onclick = async () => {
        try {
            const amount = ethers.parseEther(el.querySelector('#sellBkcAmount').value);
            await bkc.swap.sellBkc(amount);
            toast('Swap complete!', 'success');
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

function genFusionPage() {
    return `// NFT Fusion Module
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _stats = null;

export async function load(bkc) {
    _stats = await bkc.fusion.getStats();
}

export async function render(el, bkc) {
    if (!_stats) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">NFT Fusion — Fuse & Split</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Total Fusions</div>
                <div class="stat-value accent">\${_stats.totalFusions.toString()}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Total Splits</div>
                <div class="stat-value">\${_stats.totalSplits.toString()}</div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Fuse 2 NFTs → 1 Higher Tier</div>
            <p style="color:var(--text-dim);margin-bottom:12px;">Burn 2 same-tier NFTs to mint 1 of the next tier up (e.g., 2 Bronze → 1 Silver).</p>
            <div class="form-group">
                <label class="form-label">Token ID #1</label>
                <input type="number" id="fuseToken1" class="input" placeholder="101" />
            </div>
            <div class="form-group">
                <label class="form-label">Token ID #2</label>
                <input type="number" id="fuseToken2" class="input" placeholder="102" />
            </div>
            <button id="fuseBtn" class="btn btn-primary">Fuse</button>
        </div>
        <div class="card">
            <div class="card-title">Split 1 NFT → 2 Lower Tier</div>
            <p style="color:var(--text-dim);margin-bottom:12px;">Burn 1 NFT to mint 2 of the next tier down (e.g., 1 Silver → 2 Bronze).</p>
            <div class="form-group">
                <label class="form-label">Token ID to Split</label>
                <input type="number" id="splitToken" class="input" placeholder="201" />
            </div>
            <button id="splitBtn" class="btn btn-primary">Split</button>
        </div>
    \`;

    el.querySelector('#fuseBtn').onclick = async () => {
        try {
            const t1 = BigInt(el.querySelector('#fuseToken1').value);
            const t2 = BigInt(el.querySelector('#fuseToken2').value);
            const result = await bkc.fusion.fuse(t1, t2);
            toast(\`Fused! New token: #\${result.newTokenId}\`, 'success');
            await load(bkc);
            render(el, bkc);
        } catch (err) { toast(err.message, 'error'); }
    };

    el.querySelector('#splitBtn').onclick = async () => {
        try {
            const tokenId = BigInt(el.querySelector('#splitToken').value);
            const result = await bkc.fusion.split(tokenId);
            toast(\`Split! New tokens: \${result.newTokenIds.map(id => '#' + id).join(', ')}\`, 'success');
            await load(bkc);
            render(el, bkc);
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

function genBuybackPage() {
    return `// Buyback Mining Module
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _preview = null;

export async function load(bkc) {
    _preview = await bkc.buyback.preview();
}

export async function render(el, bkc) {
    if (!_preview) await load(bkc);

    el.innerHTML = \`
        <h1 class="page-title">Buyback Mining</h1>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">ETH Available</div>
                <div class="stat-value accent">\${Number(ethers.formatEther(_preview.ethAvailable)).toFixed(6)} ETH</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Mining Rate</div>
                <div class="stat-value">\${Number(_preview.currentMiningRateBps) / 100}%</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Caller Reward</div>
                <div class="stat-value">\${Number(ethers.formatEther(_preview.estimatedCallerReward)).toFixed(2)} BKC</div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Execute Buyback</div>
            <p style="color:var(--text-dim);margin-bottom:12px;">
                Convert accumulated ETH fees into BKC. You earn 5% of mined BKC as a caller reward.
            </p>
            <button id="buybackBtn" class="btn btn-primary" \${_preview.isReady ? '' : 'disabled'}>
                \${_preview.isReady ? 'Execute Buyback' : 'Not Ready Yet'}
            </button>
        </div>
    \`;

    el.querySelector('#buybackBtn').onclick = async () => {
        try {
            await bkc.buyback.execute();
            toast('Buyback executed! Check your BKC balance.', 'success');
            await load(bkc);
            render(el, bkc);
        } catch (err) { toast(err.message, 'error'); }
    };
}
`;
}

// ── Core Page Generators (always included) ─────────────────────────────────

function genTutorPage(config) {
    return `// Tutor System — Referral earnings & tutor management
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _data = {};

export async function load(bkc) {
    const [tutor, count, earnings] = await Promise.all([
        bkc.getTutor(),
        bkc.getTutorCount(),
        bkc.getPendingEarnings(bkc.address),
    ]);
    _data = { tutor, count, earnings };
}

export async function render(el, bkc) {
    if (!_data.tutor && _data.tutor !== ethers.ZeroAddress) await load(bkc);
    const hasTutor = _data.tutor && _data.tutor !== ethers.ZeroAddress;
    const shortTutor = hasTutor ? _data.tutor.slice(0, 6) + '...' + _data.tutor.slice(-4) : 'None';

    el.innerHTML = \`
        <h1 class="page-title">Tutor System</h1>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Your Tutor</div>
                <div class="stat-value" style="font-size:0.9rem;">\${shortTutor}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Your Students</div>
                <div class="stat-value accent">\${_data.count}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Pending Earnings</div>
                <div class="stat-value">\${Number(ethers.formatEther(_data.earnings)).toFixed(6)} ETH</div>
            </div>
        </div>

        \${_data.earnings > 0n ? \`
        <div class="card">
            <div class="card-title">Withdraw Earnings</div>
            <p style="color:var(--text-dim);margin-bottom:12px;">
                You have \${Number(ethers.formatEther(_data.earnings)).toFixed(6)} ETH in pending referral earnings.
            </p>
            <button id="withdrawBtn" class="btn btn-primary">Withdraw ETH</button>
        </div>
        \` : ''}

        \${!hasTutor ? \`
        <div class="card">
            <div class="card-title">Set Your Tutor</div>
            <p style="color:var(--text-dim);margin-bottom:12px;">
                A tutor earns 10% of all ETH fees you generate. Set a tutor to support someone in the ecosystem.
            </p>
            <div class="form-group">
                <label class="form-label">Tutor Address</label>
                <input type="text" id="tutorAddr" class="input" placeholder="0x..." />
            </div>
            <button id="setTutorBtn" class="btn btn-primary">Set Tutor</button>
        </div>
        \` : ''}

        <div class="card">
            <div class="card-title">How It Works</div>
            <p style="color:var(--text-dim);line-height:1.6;">
                <strong style="color:var(--accent);">Earn 10% ETH</strong> — Every time your students pay a fee, you get 10% in ETH automatically.<br><br>
                <strong style="color:var(--accent);">Earn 5% BKC</strong> — When students claim staking rewards, you earn 5% bonus BKC.<br><br>
                <strong>Dual rewards</strong> — You earn from both your students' transactions AND your own activity.<br><br>
                <strong>On-chain & trustless</strong> — All referral earnings are tracked and distributed by the smart contract.
            </p>
        </div>
    \`;

    el.querySelector('#withdrawBtn')?.addEventListener('click', async () => {
        try {
            const result = await bkc.withdrawEarnings();
            toast('Earnings withdrawn! TX: ' + result.hash.slice(0, 10) + '...', 'success');
            await load(bkc);
            render(el, bkc);
        } catch (err) { toast(err.message, 'error'); }
    });

    el.querySelector('#setTutorBtn')?.addEventListener('click', async () => {
        try {
            const addr = el.querySelector('#tutorAddr').value.trim();
            if (!ethers.isAddress(addr)) { toast('Invalid address', 'error'); return; }
            const result = await bkc.setTutor(addr);
            toast('Tutor set! TX: ' + result.hash.slice(0, 10) + '...', 'success');
            await load(bkc);
            render(el, bkc);
        } catch (err) { toast(err.message, 'error'); }
    });
}
`;
}

function genTokenomicsPage(config) {
    return `// Tokenomics — Token supply, fees, ecosystem info
import { ethers } from 'ethers';

let _stats = null;

export async function load(bkc) {
    try { _stats = await bkc.getEcosystemStats(); } catch {}
}

export async function render(el, bkc) {
    if (!_stats) await load(bkc);

    const fmtEth = (v) => v ? Number(ethers.formatEther(v)).toFixed(4) : '0';
    const fmtBkc = (v) => v ? Number(ethers.formatEther(v)).toLocaleString() : '0';

    el.innerHTML = \`
        <h1 class="page-title">Tokenomics</h1>

        <div class="card">
            <div class="card-title">BKC Token</div>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-label">Max Supply</div>
                    <div class="stat-value accent">200M BKC</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">TGE (Initial)</div>
                    <div class="stat-value">20M BKC</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">ETH Collected</div>
                    <div class="stat-value">\${fmtEth(_stats?.ethCollected)} ETH</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">Fee Events</div>
                    <div class="stat-value">\${_stats?.feeEvents?.toString() || '0'}</div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-title">Token Distribution</div>
            <p style="color:var(--text-dim);line-height:1.8;">
                <strong style="color:var(--accent);">50% — Mining Rewards</strong><br>
                Earned through staking, buyback mining, and ecosystem participation.<br><br>
                <strong style="color:var(--accent);">40% — Staking Pool</strong><br>
                Distributed to BKC delegators proportional to pStake.<br><br>
                <strong style="color:var(--accent);">10% — TGE (Initial Liquidity)</strong><br>
                Used for initial DEX liquidity and ecosystem bootstrapping.
            </p>
        </div>

        <div class="card">
            <div class="card-title">Fee Distribution</div>
            <p style="color:var(--text-dim);line-height:1.8;">
                Every transaction generates an ETH fee, distributed as follows:<br><br>
                <strong style="color:var(--accent);">10-20% → Operator</strong> — App operators earn commission on every fee.<br>
                <strong style="color:var(--accent);">10% → Tutor</strong> — Referral earnings for the user's tutor.<br>
                <strong style="color:var(--accent);">30-50% → Buyback & Burn</strong> — ETH buys BKC from the market and burns it.<br>
                <strong style="color:var(--accent);">10-30% → Treasury</strong> — Ecosystem development fund.
            </p>
        </div>

        <div class="card">
            <div class="card-title">6 Ways to Earn</div>
            <p style="color:var(--text-dim);line-height:1.8;">
                1. <strong>Stake BKC</strong> — Delegate and earn rewards over time<br>
                2. <strong>NFT Boosters</strong> — Hold NFTs to boost staking rewards<br>
                3. <strong>Tutor Referrals</strong> — Earn 10% ETH + 5% BKC from students<br>
                4. <strong>Buyback Mining</strong> — Execute buybacks for 5% caller reward<br>
                5. <strong>Fortune Pool</strong> — Win prediction games<br>
                6. <strong>Operate an App</strong> — Build with the SDK, earn 10-20% of all fees
            </p>
        </div>

        <div class="card">
            <div class="card-title">Operator</div>
            <p style="font-family:monospace;color:var(--accent);word-break:break-all;">${config.operator}</p>
            <p style="color:var(--text-dim);font-size:0.85rem;margin-top:8px;">
                This app's operator earns 10-20% of every ETH fee. Network: ${config.network}
            </p>
        </div>
    \`;
}
`;
}

function genInvitePage(config) {
    return `// Invite & Earn — Share referral link
import { ethers } from 'ethers';
import { toast } from '../main.js';

let _data = {};

export async function load(bkc) {
    const [count, earnings] = await Promise.all([
        bkc.getTutorCount(),
        bkc.getPendingEarnings(bkc.address),
    ]);
    _data = { count, earnings };
}

export async function render(el, bkc) {
    if (!_data.count && _data.count !== 0) await load(bkc);

    const link = window.location.origin + '/#dashboard?ref=' + bkc.address;
    const msg = encodeURIComponent('Join Backchain and start earning! ' + link);

    el.innerHTML = \`
        <h1 class="page-title">Invite & Earn</h1>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Your Invites</div>
                <div class="stat-value accent">\${_data.count}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Pending Earnings</div>
                <div class="stat-value">\${Number(ethers.formatEther(_data.earnings)).toFixed(6)} ETH</div>
            </div>
        </div>

        <div class="card">
            <div class="card-title">Your Referral Link</div>
            <div style="display:flex;gap:8px;align-items:center;">
                <input type="text" class="input" value="\${link}" readonly id="refLink" style="flex:1;font-size:0.8rem;" />
                <button id="copyBtn" class="btn btn-primary" style="white-space:nowrap;">Copy</button>
            </div>
        </div>

        <div class="card">
            <div class="card-title">Share</div>
            <div style="display:flex;gap:12px;flex-wrap:wrap;">
                <a href="https://twitter.com/intent/tweet?text=\${msg}" target="_blank" class="btn btn-secondary">Twitter / X</a>
                <a href="https://t.me/share/url?url=\${encodeURIComponent(link)}&text=\${encodeURIComponent('Join Backchain!')}" target="_blank" class="btn btn-secondary">Telegram</a>
                <a href="https://wa.me/?text=\${msg}" target="_blank" class="btn btn-secondary">WhatsApp</a>
            </div>
        </div>

        <div class="card">
            <div class="card-title">How It Works</div>
            <p style="color:var(--text-dim);line-height:1.8;">
                1. <strong>Share your link</strong> — Send it to friends, post on social media.<br><br>
                2. <strong>They join & connect</strong> — Your friend connects their wallet through your link.<br><br>
                3. <strong>You become their tutor</strong> — Registered on-chain automatically (gasless).<br><br>
                4. <strong>Earn forever</strong> — Get <strong style="color:var(--accent);">10% ETH</strong> of every fee + <strong style="color:var(--accent);">5% BKC</strong> of their staking rewards. Permanently.
            </p>
        </div>
    \`;

    el.querySelector('#copyBtn').addEventListener('click', () => {
        navigator.clipboard.writeText(el.querySelector('#refLink').value)
            .then(() => toast('Link copied!', 'success'))
            .catch(() => toast('Copy failed', 'error'));
    });
}
`;
}

// ── Helpers ─────────────────────────────────────────────────────────────────

function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}
